### PR TITLE
Add CORS headers to HTTP responses

### LINKED ISSUE #76: Enable cross origin resource sharing?
A while ago I was planning creating a web-based client for Discuit, but as Discuit doesn't set any CORS headers, I ran into the following error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://discuit.net/api/_initial. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Are there any reasons why CORS headers aren't currently set? I think enabling CORS would be great for third-party developers :)

### PR DESCRIPTION
**Pull request by ttaylor-st**
Closes #76 

Everything should be working fine. I tested by replacing requests to `discuit.net/api/*` with `localhost/api/*` in the official client at [discuit.net](https://discuit.net) and everything worked perfectly fine.

### CODE REVIEW

**Comment by ttaylor-st** [comment]
@previnder sorry for the mention, [someone else has asked about CORS](https://discuit.net/DiscuitDev/post/SO2YrAc0) on Discuit, do you know if/when this'll be merged?

**Comment by previnder** [comment]
Okay, tested this a bunch. There is a problem with allowing credentialed cross-site requests, in that it allows for CSRF requests to go through. Right now, it doesn't matter either way because the `SID` cookie is set with `SameSite=Lax`, so it won't be sent over with cross-site requests. But if the `SameSite` attribute was set to `None`, it would allow any domain to forge requests.

Moreover, it doesn't seem like it's possible to allow just any domain to host a web-client of a site, with support for authenticated requests, without huge CSRF vulnerabilities.

**Comment by mmStiver** [comment]
Hey, what's the decision on this? 

I'm working on a bot that is blocked by CORS requests on images. I personally don't need authenticated requests, but it would be helpful to be able to do basic get images.

**Comment by previnder** [comment]
Hey @mmStiver, I just added CORS headers for image file responses in b24bc66c. You should be good to go!

**Pull request closed without merging**
