### PR TITLE
Improvements for lists 

### PR DESCRIPTION
**Pull request by ttaylor-st**
Addresses most things in #90 (creating lists from the lists page, removing items from a list without the additional steps), makes the /{user}/lists page responsive and also removes the visibility filter if the user doesn't own the list.

Something to note: Instead of providing a link to a user's lists page, I added a card with a list of all the user's lists in the About section

To do:
- [x] Moving items from one list to another
- [x] Rerender the lists when another is added instead of refreshing

### CODE REVIEW

**Comment by previnder** [comment]
Looks good. Thanks. I was wondering where to add a link to the lists page on the user profile page, but showing all the user's lists in the sidebar there instead is probably a better idea. Perhaps we could add a link to the lists page as a last item in the lists list here: 

lists

**Comment by noClaps** [comment]
You could make the header of that section the link to the lists page.

**Comment by previnder** [comment]
That could also work. Or a "View all" button here: 

lists2

**Comment by ttaylor-st** [comment]
Yeah, I think a button in the top right would be a bit clearer to the user

**Comment by ttaylor-st** [comment]
That makes sense, it does seem a bit redundant now that I think about it.

**Pull request merged**
