### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by Codycody31**
- This PR supports building a docker image containing Discuit. It also updates from using a root user for the database to the `discuit` user
- Instructions are added to create the image and run the container
- Though if the config.yaml needs to be persisted, you will need to mount the file to the container
- Image is currently restricted to running on amd64 systems

Would close issue #4

### CODE REVIEW

**Comment by PendaGTP** [comment]
I have some concerns about changing the database username and password in the default/example config file.
Typically, when installing MariaDB, there is just a root user which has no password. I believe this is why the default values are set as they are.

Could you clarify the use case for adding this docker support?

I'd like to draw your attention to this [PR](https://github.com/discuitnet/discuit/pull/34), which add Docker Compose to run external services (MariaDB and Redis). The goal here is to assist new contributors in setting up their local development environment more easily.

**Comment by Codycody31** [comment]
Setting the creds to discuit are 1. to ensure that we can correctly create the user (in the docker container), and 2. to switch from using a high-privileged user such as root to one with access to only one database (where the user should only have access to 1 db). 

Also, while PR #34 adds a docker compose. This allows server hosts to pull the code, build the docker image, and run it without having to have things like Golang, Nodejs, etc installed (though for now limited to amd64 arch cpu's). So it's more directed to deploying the site rather than developing it.

**Comment by PendaGTP** [comment]
Sorry, but I still don't see the use case. For who? For what?
Anyway, I'll let @previnder review this one.

**Comment by Codycody31** [comment]
One, for who: server hosts, and those wishing to deploy discuit on their own, but don't wish to install the needed software such as Golang, Nodejs, libvps, etc. For example, on my [personal harbor instance](https://harbor.vmgware.dev/harbor/projects/1/repositories/discuit/artifacts-tab?publicAndNotLogged=yes) I could then just pull and the deploy discuit on two commands, without any extra work required.

So this docker support is particularly beneficial for those who may not be familiar with the intricacies of software dependencies or for developers looking for a quick and efficient way to get the application running. It removes the complexity of software installation and configuration, leading to a smoother setup experience.

**Comment by previnder** [comment]
Looks good. Thanks. I'm going to merge this PR, and discard #34, as this one adds Docker support more fully.

To be clear, the production instance at discuit.net doesn't use any form of containerization; because I don't see any benefit to that added complexity, since everything's in one instance (and also because of Go making deployment a breeze). So, the only use case as of now of this is that this would make it a bit easier to contribute to this project.

**Pull request merged**
